### ISSUE TITLE
bodega.id, campo.id, vid.id must be autoincremental field with consecutive numbers

### ISSUE THREAD

**Issue by Japoivvb** [Jirsaao/UF2P2---Hibernate-Java#2]
1. ids generated by Hibernate using corresponding models should be autoincremental to allow insert data in field instruction with an error regarding duplicated query.

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 
e.g. #1 adds incremental id logic

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Jirsaao** [comment]
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/0586a4a6-40e3-4423-a96a-a1eed28c8e59)
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/e5e33b00-8981-4107-9b39-0f7230b6c34f)
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/ab5e440f-4913-4639-8a99-291c1368498f)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
