### ISSUE TITLE
add new field nombre to campo model 

### ISSUE THREAD

**Issue by Japoivvb** [Jirsaao/UF2P2---Hibernate-Java#4]
1. add nombre attribute to campo model and verify everything is working again

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Jirsaao** [comment]
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/a3007c60-2b48-4a2f-b8a4-55266edd4f32)

**Comment by Jirsaao** [comment]
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/759b870d-f568-4cc5-80b0-0caecdc560a4)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
