### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [Jirsaao/UF2P2---Hibernate-Java#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Jirsaao** [comment]
Collecion Entrada
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/a7caca74-a89a-4b92-a49f-e68abb6bd0be)

Collection Bodega
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/60a162cc-11fe-4938-9ffa-4aae025c82fb)

Collection Campo
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/fe097960-02e4-4074-8ef5-caaa13ef4793)

Collection Vid
![image](https://github.com/Jirsaao/UF2P2---Hibernate-Java/assets/145552020/f1cc758d-b451-4bcf-af2c-2833d93126b4)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
well done
